name: Update README with latest YouTube videos

on:
  push:
    paths:
      - '.github/workflows/update-readme.yml'
      - 'scripts/**'
      - 'README.md'
  schedule:
    - cron: '0 8 * * *'   # runs daily at 08:00 UTC (adjust if you want)
  workflow_dispatch: {}   # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install requests feedparser

      - name: Fetch latest videos and update README
        run: |
          python scripts/update_readme_youtube.py \
            --channel-id UCqgZYZ_MGdkm5sMsZf7mwUA \
            --readme README.md \
            --max-videos 3

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "ci: update README with latest YouTube videos"
            git push origin HEAD:$(echo "${GITHUB_REF#refs/heads/}")
          else
            echo "No changes to commit"
          fi
